import { BaseState } from "./BaseState.js";
import { getStudentData } from "../FDND/Fdnd.js"

export class WhoamiState extends BaseState {

    constructor(context) {
        super(context);

        this.context.terminal.clear();

        this.context.terminal.showLine("Whoami?");

        this.context.terminal.showLine(" ");

        this.context.terminal.showLine("man [command]         Get more info about a command");

        this.context.terminal.showLine(" ");


        this.context.terminal.showLine("whois [id]            Get information about another user");
        this.context.terminal.showLine("goal [id]             Get information about one of my minor goals");
        this.context.terminal.showLine("whoami [category]     Get to know something about me");
        this.context.terminal.showLine("reset                 Reset Kerrminal");

        this.context.terminal.showLine(" ");
    }

    async getPersonalData(id) {
        let personalData = await getStudentData(id);

        // TODO check null on any of the data
        if (personalData) {
            if (personalData.name) {
                this.context.terminal.showLine("Naam:       " + personalData.name);
            }

            if (personalData.nickname) {
                this.context.terminal.showLine("Bijnaam:    " + personalData.nickname);
            }

            if (personalData.birthdate) {
                this.context.terminal.showLine("Verjaardag: " + this.formatDate(personalData.birthdate));
            }

            if (personalData.github_handle) {
                this.context.terminal.showLine("GitHub:     " + personalData.github_handle);
            }

            if (personalData.website) {
                this.context.terminal.showLine("Website:    " + personalData.website);
            }

            if (personalData.bio) {
                this.context.terminal.showLine("Bio:        " + personalData.bio);
            }
        } else {
            this.context.terminal.showLine("Failed to fetch personal data.");
        }
    }

    // Generated by ChatGPT
    formatDate(dateString) {
        if (!dateString) return null;
        const date = new Date(dateString);
        const day = String(date.getDate()).padStart(2, "0");
        const month = String(date.getMonth() + 1).padStart(2, "0");
        const year = date.getFullYear();
        return `${day}-${month}-${year}`;
    }

    async handleCommand(command) {
        let tokens = command.split(" ");

        switch (tokens[0]) {
            case "whois":
                if (!this.isValidNumber(tokens.slice(1))) return;
                await this.getPersonalData(tokens[1]);
                break;
            case "whoami":
                break;
            case "goal":
                if (!this.isValidGoal(tokens.slice(1))) return;

                if (tokens[1] == 0) {
                    this.context.terminal.showLine("Tijdens mijn major komt het menselijke aspect van software ontwikkeling weinig aan bod. Ik wil tijdens de minor leren om een website te ontwerpen die gebruiksvriendelijk is en principes die hieraan ten grondslag liggen beter begrijpen.");
                } else if (tokens[1] == 1) {
                    this.context.terminal.showLine("Ik wil leren meer te itereren over mijn werk en minder tijd te spenderen aan kleine details verbeteren. Ik wil dus minder gericht zijn op een groot en ambitieus doel, en me meer richten op een klein prototypes maken en deze uitbreiden tot een steeds complexer geheel.");
                } else if (tokens[1] == 2) {
                    this.context.terminal.showLine("TODO");
                }
                break;
            default: // Unknown command, check if global command
                super.handleCommand(command)
        }
    }

    isValidNumber(tokens) {

        if (tokens.length !== 1) {
            this.context.terminal.showLine("Expecting 1 parameter but received " + tokens.length);
            return false;
        }

        const n = Number(tokens[0]);
        if (!(Number.isInteger(n) && tokens[0].trim() !== "")) {
            this.context.terminal.showLine(tokens[0] + " is not a valid number");
            return false;
        }

        else return true;
    }

    isValidGoal(tokens) {
        if (tokens.length !== 1) {
            this.context.terminal.showLine("Expecting 1 parameter but received " + tokens.length);
            return false;
        }

        const n = Number(tokens[0]);
        if (!(Number.isInteger(n) && tokens[0].trim() !== "")) {
            this.context.terminal.showLine(tokens[0] + " is not a valid number");
            return false;
        }

        else return true;
    }
}