import { BaseState } from "./BaseState.js";
import { getStudentData } from "../FDND/Fdnd.js";

export class WhoamiState extends BaseState {
  constructor(context) {
    super(context);

    this.context.terminal.clear();

    this.context.terminal.showLine("Whoami?");

    this.context.terminal.showLine(" ");

    this.context.terminal.showLine(
      "man [command]         Get more info about a command",
    );

    this.context.terminal.showLine(" ");

    this.context.terminal.showLine(
      "whois [id]            Get information about another user",
    );
    this.context.terminal.showLine(
      "goal [id]             Get information about one of my minor goals",
    );
    this.context.terminal.showLine(
      "whoami [category]     Get to know something about me",
    );
    this.context.terminal.showLine("reset                 Reset Kerrminal");

    this.context.terminal.showLine(" ");
  }

  getPersonalData(id) {
    let personalData = getStudentData(123).then((data) => {
      console.log(data);
    });

    // TODO check null on any of the data
    if (personalData) {
      if (personalData.name) {
        this.context.terminal.showLine("Naam:       " + personalData.name);
      }

      if (personalData.nickname) {
        this.context.terminal.showLine("Bijnaam:    " + personalData.nickname);
      }

      if (personalData.birthdate) {
        this.context.terminal.showLine(
          "Verjaardag: " + this.formatDate(personalData.birthdate),
        );
      }

      if (personalData.github_handle) {
        this.context.terminal.showLine(
          "GitHub:     " + personalData.github_handle,
        );
      }

      if (personalData.website) {
        this.context.terminal.showLine("Website:    " + personalData.website);
      }

      if (personalData.bio) {
        this.context.terminal.showLine("Bio:        " + personalData.bio);
      }
    } else {
      this.context.terminal.showLine("Failed to fetch personal data.");
    }
  }

  // Generated by ChatGPT
  formatDate(dateString) {
    if (!dateString) return null;
    const date = new Date(dateString);
    const day = String(date.getDate()).padStart(2, "0");
    const month = String(date.getMonth() + 1).padStart(2, "0");
    const year = date.getFullYear();
    return `${day}-${month}-${year}`;
  }

  async handleCommand(command) {
    let tokens = command.split(" ");

    switch (tokens[0]) {
      case "whois":
        if (!this.isValidNumber(tokens.slice(1))) return;
        await this.getPersonalData(tokens[1]);
        break;
      case "whoami":
        if (!this.isValidName(tokens.slice(1))) return;

        const topicsMap = {
          animals: [
            "animals.jpg",
            "I'm a big fan of animals, my favourite is a quoka. Recently I've become a vegetarian. The background is a picture that my girlfriend took of me and some random guy.",
          ],
          baking: [
            "baking.jpg",
            "Although I currently do not have an oven sadly, I do love to bake. My favourite cake to make is appeltaart, since my girlfriend loves them. The backgroundimage shows some cupcakes I've made and decorated.",
          ],
          boardgame: [
            "boardgames.jpg",
            "I enjoy playing boardgames with friends. You can expect me to bring a few whenever I hang out with them. In the background you see me playing the game Trails.",
          ],
          girlfriend: [
            "girlfriend.jpg",
            "My girlfriend and I have been together for almost 5 years know. Our first date was in the zoo. The second date was an puzzle tour in Rotterdam, which you can see in the background.",
          ],
          halloween: [
            "halloween.png",
            "One of my favourite holidays is Halloween. I was born the day before halloween, so I usually celibrate them together. In the background you can see some jack o' lanterns me and my friends made.",
          ],
          harrypotter: [
            "harry_potter.jpg",
            "I love Harry Potter. I'm in the process of collecting all Harry Potter games, of which I now have a total of 30.",
          ],
          study: [
            "retrogames.jpg",
            "I enjoy gaming, but specifically retro games. Some can be incredibly disapointing, although most are a blast. In the picture, I'm playing Advance Wars on a Gameboy Advance, which is about as old as I am.",
          ],
          sports: [
            "sports.jpg",
            "I'm that into sports, but I can have a lot of fun with different activities. In the picture I am playing minigolf in lage vuursche.",
          ],
          retrogames: [
            "study.jpg",
            "I do not study CMD. I study Technical Informatics at Avans. I code programs that will be used by machines rather than humans. In the picture I have a working prototype on an Computer Vision algorithm to track a steering wheel.",
          ],
          default: ["background.jpg", "BOOO! Boooring!"],
        };

        const desktop = document.querySelector(".desktop");
        desktop.style.backgroundImage = `url(./resources/${topicsMap[tokens[1]][0]})`;
        this.context.terminal.showLine(topicsMap[tokens[1]][1]);
        break;
      case "goal":
        if (!this.isValidGoal(tokens.slice(1))) return;

        if (tokens[1] == 0) {
          this.context.terminal.showLine(
            "Tijdens mijn major komt het menselijke aspect van software ontwikkeling weinig aan bod. Ik wil tijdens de minor leren om een website te ontwerpen die gebruiksvriendelijk is en principes die hieraan ten grondslag liggen beter begrijpen.",
          );
        } else if (tokens[1] == 1) {
          this.context.terminal.showLine(
            "Ik wil leren meer te itereren over mijn werk en minder tijd te spenderen aan kleine details verbeteren. Ik wil dus minder gericht zijn op een groot en ambitieus doel, en me meer richten op een klein prototypes maken en deze uitbreiden tot een steeds complexer geheel.",
          );
        } else if (tokens[1] == 2) {
          this.context.terminal.showLine(
            "Ik verwacht relatief snel vaardiger te worden in JavaScript. Ik hoop echter tijdens de minor vooral stappen te zetten met HTML en in het bijzonder CSS. Concreet zou ik het heel leuk vinden als ik aan het einde van de minor mooie en effectieve microinteracties met animaties te kunnen maken.",
          );
        }
        break;
      default: // Unknown command, check if global command
        super.handleCommand(command);
    }
  }

  isValidName(tokens) {
    if (tokens.length !== 1) {
      this.context.terminal.showLine(
        "Expecting 1 parameters but received " + tokens.length,
      );
      return false;
    }

    const topics = [
      "animals",
      "baking",
      "boardgame",
      "girlfriend",
      "halloween",
      "harrypotter",
      "study",
      "sports",
      "retrogames",
      "default",
    ];

    if (!topics.includes(tokens[0])) {
      this.context.terminal.showLine("The requested topic does not exist");
      return false;
    }

    return true;
  }

  isValidNumber(tokens) {
    if (tokens.length !== 1) {
      this.context.terminal.showLine(
        "Expecting 1 parameter but received " + tokens.length,
      );
      return false;
    }

    const n = Number(tokens[0]);
    if (!(Number.isInteger(n) && tokens[0].trim() !== "")) {
      this.context.terminal.showLine(tokens[0] + " is not a valid number");
      return false;
    } else return true;
  }

  isValidGoal(tokens) {
    if (tokens.length !== 1) {
      this.context.terminal.showLine(
        "Expecting 1 parameter but received " + tokens.length,
      );
      return false;
    }

    const n = Number(tokens[0]);
    if (!(Number.isInteger(n) && tokens[0].trim() !== "")) {
      this.context.terminal.showLine(tokens[0] + " is not a valid number");
      return false;
    }

    return true;
  }
}
