import { Command } from "./Command.js";

export class WhoamiCommand extends Command {
  topicsMap = {
    animals:
      "I'm a big fan of animals, my favourite is a quoka. Recently I've become a vegetarian. The wallpaper \"animals\" (see settings) is a picture that my girlfriend took of me with a monkey.",
    baking:
      'Although I currently do not have an oven sadly, I do love to bake. My favourite cake to make is appeltaart, since my girlfriend loves them. The wallpaper "baking" (see settings) shows some cupcakes I\'ve made and decorated.',
    boardgame:
      'I enjoy playing boardgames with friends. You can expect me to bring a few whenever I hang out with them. On the wallpaper "boardgames" (see settings) you can see me playing the game Trails.',
    girlfriend:
      'My girlfriend and I have been together for almost 5 years now. Our first date was in the zoo. The second date was a puzzle tour in Rotterdam, during which we took the picture shown on the wallpaper "girlfriend" (see settings).',
    halloween:
      'One of my favourite holidays is Halloween. I was born the day before Halloween, so I usually celebrate them together. On the wallpaper "halloween" (see settings) you can see some jack o\' lanterns me and my friends made.',
    harrypotter:
      'I love Harry Potter. I\'m in the process of collecting all Harry Potter games, of which I now have a total of 30. On the wallpaper "harry" (see settings) you see some of the ones that are available, but there are more!',
    gaming:
      'I enjoy gaming, but specifically retro games. Some can be incredibly disappointing, although most are a blast. On the wallpaper "gaming" (see settings), I\'m playing Advance Wars on a Gameboy Advance, which is about as old as I am.',
    activities:
      'I\'m not that into sports, but I can have a lot of fun with different activities. On the wallpaper "activities" (see settings) I am playing minigolf in Lage Vuursche.',
    study:
      'I do not study CMD. I study Technical Informatics at Avans. I code programs that will be used by machines rather than humans. On the wallpaper "study" (see settings) I have a working prototype on a Computer Vision algorithm to track a steering wheel.',
  };

  constructor() {
    super(
      "whoami",
      "[category]",
      "Get to know something about me in [category]",
      "Get to know something about me in [category]",
    );
  }

  async execute(...args) {
    if (!this.isValidName(args)) {
      return [
        "Unknown category.",
        "Try one of:",
        ...Object.keys(this.topicsMap).map((t) => `- ${t}`), // This line was generated by ChatGPT
      ];
    }

    const topic = args[0];
    return [this.topicsMap[topic]];
  }

  isValidName(args) {
    return args.length === 1 && Object.keys(this.topicsMap).includes(args[0]);
  }
}
